DROP DATABASE IF EXISTS intensityservice ;
DROP USER IF EXISTS `intensity_service`@`%`;
CREATE DATABASE IF NOT EXISTS intensityservice CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `intensity_service`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `intensityservice`.* TO `intensity_service`@`%`;
FLUSH PRIVILEGES;